name: "Saeki Assignment"
networks:
  app-network:
    driver: bridge
services:
  api:
    container_name: api
    user: root
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ENV: ${ENV}
    restart: always
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./apps/api/public:/app/public
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://nginx.saekiassignment.orb.local
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app-network
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web
    networks:
      - app-network
