name: "Saeki Assignment"
networks:
  app-network:
    driver: bridge
services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  #   networks:
  #     - app-network
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: UnsafePassword123!
    networks:
      - app-network
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   # depends_on:
  #   # - api
  #   # - web
  #   networks:
  #     - app-network
